name: CI
on: [push]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Components
        run: npm install

      - name: Run LQG Pool tests
        run: npm test
